Algoritmo "DiadaSemana"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/05/2019
Var Banco:Inteiro

Inicio
      Escreva ("Quanto tem de remessinha do banco?.:")
      Leia (Banco)
      Escolha(Banco)
           Caso 1
              ESCREVA ("BBD:R$12.000.000,00")
           caso 2
              ESCREVA ("CEF:R$15.000.000,00")
           Caso 3
              ESCREVA ("Itaú:R$8.000.000,00")
           Caso 4
              ESCREVA ("SCD União:R$2.343.000,00")
           Caso 5
              ESCREVA ("SCD Agro:R$248.000,00")
           Caso 6
              ESCREVA ("SCD Valor:R$150.000,00")
           Caso 7
              ESCREVA ("Sicoob:R$1.250.000,00")
              Outrocaso
              Escreval ("Tesouraria não está cadastrada em nosso banco de dados")
      Fimescolha
Fimalgoritmo